import { DataListInterface } from '../../../types/types';

export const characters: DataListInterface[] = [
  {
    name: 'Luke Skywalker',
    birth_year: '19BBY',
    gender: 'male',
    height: '172',
    hair_color: 'blond',
    eye_color: 'blue',
  },
  {
    name: 'Leia Organa',
    birth_year: '19BBY',
    gender: 'female',
    height: '150',
    hair_color: 'brown',
    eye_color: 'brown',
  },
  {
    name: 'Han Solo',
    birth_year: '29BBY',
    gender: 'male',
    height: '180',
    hair_color: 'brown',
    eye_color: 'hazel',
  },
  {
    name: 'Darth Vader',
    birth_year: '41.9BBY',
    gender: 'male',
    height: '202',
    hair_color: 'none',
    eye_color: 'yellow',
  },
  {
    name: 'Obi-Wan Kenobi',
    birth_year: '57BBY',
    gender: 'male',
    height: '182',
    hair_color: 'auburn',
    eye_color: 'blue-gray',
  },
  {
    name: 'Yoda',
    birth_year: '896BBY',
    gender: 'male',
    height: '66',
    hair_color: 'white',
    eye_color: 'green',
  },
  {
    name: 'Padmé Amidala',
    birth_year: '46BBY',
    gender: 'female',
    height: '165',
    hair_color: 'brown',
    eye_color: 'brown',
  },
  {
    name: 'Mace Windu',
    birth_year: '72BBY',
    gender: 'male',
    height: '188',
    hair_color: 'none',
    eye_color: 'brown',
  },
  {
    name: 'Anakin Skywalker',
    birth_year: '41.9BBY',
    gender: 'male',
    height: '188',
    hair_color: 'blond',
    eye_color: 'blue',
  },
  {
    name: 'Chewbacca',
    birth_year: '200BBY',
    gender: 'male',
    height: '228',
    hair_color: 'brown',
    eye_color: 'blue',
  },
];
